name: Build Release APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.0
        env:
          SIGN_STORE_PWD: ${{ secrets.SIGN_STORE_PWD }}
          SIGN_KEY: ${{ secrets.SIGN_KEY }}
          SIGN_KEY_PWD: ${{ secrets.SIGN_KEY_PWD }}
        with:
          gradle-version: 7.3.3
          arguments: assembleRelease

      - name: upload apk
        uses: actions/upload-artifact@v3
        with:
          name: apk.zip
          path: app/build/outputs/apk/**/*.apk

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          files: |
            app-release.apk